Feature: added BaseTestNG and example of use
Tolok44/SFramework pull request #4
Opened 2021-03-12 05:17 UTC by Mexarm

BaseTestNG is a class that  creates a report for all the test cases.
an example class TestNGExample  is included

2021-03-12 21:39 UTC, IvonneRddz approved these changes

2021-03-16 20:42 UTC, Tolok44 requested changes
Add the Reports folder to the git ignore and exclude the report html files from the repository

2021-03-16 21:16 UTC, Mexarm commented
> Add the Reports folder to the git ignore and exclude the report html files from the repository

requested changes done (by Ivonne)

2021-03-16 21:17 UTC, Tolok44 approved these changes

2021-03-16 21:18 UTC, merged